### ISSUE TITLE
Issue with ECEF to ENU not scaling correctly

### ISSUE THREAD

**Issue by PostMatthew** [PostMatthew/Laptime_Simulation_ME391#24]
Having issue in the LongDocumentation Notebook with the scaling for the ENU track. Can you take a look? even when plot manually scaled its showing minimal change in the ENU but the station is reasonable. Additionally, the curvature seems to be scaled to large.

**Comment by Alexanderallenbrown** [comment]
what happens when you plot the raw lat and lon? is it possible those columns are switched?

additionally, i notice that "lambda" in the lla2ecef function is hard-coded as 0.  this will definitely cause issues, since (IIRC) this would mean we're at the prime meridian, I think.
<img width="843" alt="image" src="https://user-images.githubusercontent.com/3538130/153467152-6f7e6ad3-84d9-44e9-bfa0-f6eb872cafc4.png">

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/3538130/153467318-831383be-3a4e-4a2b-9a21-ed2643d0807e.png">
